Fix GraphiQL build+release (#10043)
* Fix GraphiQL build+release

This build step was dropped in commit 9d985e8b83f; let's restore it.

This was causing releases to fail with errors like this:
> ```
> + echo 'Deploy GraphiQL'
> + source ./scripts/deploy-graphiql.sh
> ++ [[ -z graphiql.***.com ]]
> ++ node scripts/s3deploy.mjs packages/graphiql/dist s3://graphiql.***.com/
> Starting deployment to s3://graphiql.***.com//
> Error: ENOENT: no such file or directory, scandir 'packages/graphiql/dist'
>     at async readdir (node:internal/fs/promises:956:18)
>     at async getFiles (file:///home/runner/work/***/***/scripts/s3deploy.mjs:126:17)
>     at async main (file:///home/runner/work/***/***/scripts/s3deploy.mjs:82:20) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'scandir',
>   path: 'packages/graphiql/dist'
> }
> ```

Signed-off-by: Noah Silas <noah@medplum.com>

* Run GraphiQL release after `server` release

If the GraphiQL release fails for any reason, it's generally not urgent,
as the older version of this app will stay published. However, this
failure blocks later releases, and in particular this was occurring
before the script would get to the `server` release, which is more
likely to be an important update to get out.

Re-ordering these means that we won't attempt the GraphiQL release until
the `server` release is completed, and it can't block the high priority
service release anymore.

Signed-off-by: Noah Silas <noah@medplum.com>

---------

Signed-off-by: Noah Silas <noah@medplum.com>