Fix GraphiQL build+release
This build step was dropped in commit 9d985e8b83f; let's restore it.

This was causing releases to fail with errors like this:
> ```
> + echo 'Deploy GraphiQL'
> + source ./scripts/deploy-graphiql.sh
> ++ [[ -z graphiql.***.com ]]
> ++ node scripts/s3deploy.mjs packages/graphiql/dist s3://graphiql.***.com/
> Starting deployment to s3://graphiql.***.com//
> Error: ENOENT: no such file or directory, scandir 'packages/graphiql/dist'
>     at async readdir (node:internal/fs/promises:956:18)
>     at async getFiles (file:///home/runner/work/***/***/scripts/s3deploy.mjs:126:17)
>     at async main (file:///home/runner/work/***/***/scripts/s3deploy.mjs:82:20) {
>   errno: -2,
>   code: 'ENOENT',
>   syscall: 'scandir',
>   path: 'packages/graphiql/dist'
> }
> ```

Signed-off-by: Noah Silas <noah@medplum.com>