Revert "Dependency upgrades 2026-07-13 (#9844)"
We're hitting some frustrating complications from this upgrade.

- Server: `npm run dev` fails in some circumstances, seemingly related
  to changes in the OTel loading

- During server startup:

  > Error: 'import-in-the-middle' failed to wrap 'file:///Users/mattwiller/medplum/node_modules/@kubernetes/client-node/dist/gen/types/ObservableAPI.js'

  This seems likely to be related to https://github.com/guybedford/es-module-lexer/issues/214

For now we're reverting this set of dependency upgrades; hopefully the
ecosystem irons out some of these challenges for us by next week's run.

This reverts commit c22480671319bb1de14c08b234d384e1b3040211.

Signed-off-by: Noah Silas <noah@medplum.com>